#
# WLA DX Windows build script for CMake + MSVC
#

trigger:
- master

pool:
  vmImage: 'windows-2022'

steps:
- script: |
    cmake .
    cmake --build . --config Release -j
  displayName: 'Build Release'
  timeoutInMinutes: 120
- script: |
    cmake .
    cmake --build . --config Debug -j
  displayName: 'Build Debug'
  timeoutInMinutes: 120
